[tool.poetry]
name = "ccsnet"
version = "0.1.0"
description = "Detection for ccsn"
authors = ["Andy"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
