# This part majorly serves for datagen

#Train
# start = 1262632990
train_start = 1262653854
train_end = 1262686622
# Test
test_start = 1262919719 
test_end = 1262944254
ifos = ["H1", "L1"]
frame_type = ["HOFT_C01", "HOFT_C01"]
state_flag = ["DCS-ANALYSIS_READY_C01:1", "DCS-ANALYSIS_READY_C01:1"]
channels = ["DCS-CALIB_STRAIN_CLEAN_C01", "DCS-CALIB_STRAIN_CLEAN_C01"]

sample_rate = 4096
fftlength=2
overlap=1

# A. Should includes in with the active segements time
# B. Try to pass envioment variable to read file 
raw_ccsn = "/home/hongyin.chen/Data/CCSNet/production/CCSNe/RAW"
omicron_output = "/home/hongyin.chen/Data/stashed_CCSNet_data/CCSNet_data/Publication/omicron/training"


# Training & Validation
# data_dir = "/home/hongyin.chen/Data/CCSNet/recover_runs"
data_dir = "/home/hongyin.chen/Data/CCSNet/production/one_segmet_run"
backgrounds = "background.h5"
psd_files = "psds.h5"
glitch_info = "glitch_info.h5"

chosen_signals = "/home/hongyin.chen/anti_gravity/CCSNet/apps/train/ccsn.toml"
signals_dir = "CCSNe/Resampled"
# chosen_signals = "/home/hongyin.chen/Xperimental/CCSNet/sandbox/ccsn_2.toml"
# signals = "/home/hongyin.chen/Data/CCSNet/production/one_segmet_run/CCSNe/Resampled"

# Test
test_dir = "/home/hongyin.chen/Data/CCSNet/test_runs"
test_background = "background.h5"
test_data = "test_dataset"
test_psds = "psds.h5"

# Training phase
init_distance = 1
sample_duration = 3
model_parameter = {c_depth = 8, n_chann = 64, l1 = 1024, l2 = 128}
batch_size = 512
steps_per_epoch = 200
max_iteration = 200
max_lr = 4e-3
lr_ramp_epochs = 75 
weight_decay = 1e-5
highpass = 32
# pretrained_model = None
learning_rate = 0.004
output_dir = "/home/andy/Outputs/CCSNet_Out_dir/recover_runs_ADAMW/Result_003"
val_sqrtnum = 4

# Test
test_count = 5000
snr_distro = [8, 10, 12, 15, 20, 25, 30, 35, 40]
count = 50